### PR TITLE
Add pkg base

### PR DESCRIPTION
**Pull request by kmoore134**
These commits as PKG to base, along with libpkg, ca-root-nss and update the pc-sysinstall / pc-installdialog / make release process to properly create an ISO that can be installed with pkg base.

### CODE REVIEW

**Review by pkgdemon — COMMENTED** [review]
Have you tried supervise daemon or the option to restart crashed services?

**Comment by kmoore134** [comment]
I have a few services using it here and so far seems good :)

**Comment by kmoore134** [comment]
dhcpcd was an edge case though, can't use supervise-daemon. Since it doesn't support foreground mode.

**Review by pkgdemon — COMMENTED** [review]
We need to disable a lot more than boot_mute here.  Ideally we would just restore the original loader.conf, rc.conf, sysctl.conf from upstream.

**Comment by pkgdemon** [comment]
@kmoore134 Where is the CI for this PR?  Is there an ISO I can try?

**Comment by kmoore134** [comment]
Lol, you just want it all don't you ;)

Hang tight. Setting up CI still, since I created a new repo I need to reconfigure the Jenkins job to do the CI now. 

As for cleaning up the loader.conf, rc.conf and sysctl.conf, I'd prefer that be done in another PR / branch. This is mainly about getting a working build / install ISO.

**Comment by kmoore134** [comment]
The CI job is running now: 

https://builds.ixsystems.com/jenkins/job/TrueOS%20-%20World%20CI/view/change-requests/job/PR-1/

I'll check it in the morning, since I'm not 100% positive Jenkins is setup to do the artifact'ing properly yet.

**Comment by pkgdemon** [comment]
@kmoore134 I do think we can fix the dhpcd crashing issue without sleep.  I think it is very hackish to add sleeps to OpenRC scripts, and I know it will bite us later under certain conditions.  That probably bugs me the most about what I see here.  

In the future when we are further along with our goals I might want to "request changes" on things like sleeps in OpenRC scripts.  Otherwise more mere suggestions of where I could see improvements with this PR which is why I did not mark "request changes", and only commented.  

I realize those default config changes for loader.conf, sysctl.conf, and rc.conf will need to be coordinated with trueos-core so that trueos-desktop installs with those settings it needs.  If you catch yourself editing loader.conf again you might want to consider replacing them with stock at that point is how I was looking at it.  You might be duplicating the work is all if you have to touch those files a few more times.

I'm not too worried about the artifacts as long as the build doesn't break.  If that works my vote is to merge as long as @beanpole135 does not see anything obvious that will cause issues for TrueOS desktop.

**Comment by pkgdemon** [comment]
@kmoore134 From the dhcpcd man page for 7.0_4 which is installed on my system:
```
     -B, --nobackground
             Don't run in the background when we acquire a lease.  This is
             mainly useful for running under the control of another process,
             such as a debugger or a network manager.
```

**Comment by pkgdemon** [comment]
Clone timed out on the first so I started another:

https://builds.ixsystems.com/jenkins/job/TrueOS%20-%20World%20CI/job/PR-1/2/console

**Comment by pkgdemon** [comment]
@kmoore134 memstick.img needs to be artificated as well https://builds.ixsystems.com/jenkins/job/TrueOS%20-%20World%20CI/job/PR-1/2/

**Comment by kmoore134** [comment]
Looks like the ISO built, hurrah for artifacts ;)

As for the sleep, yea it was kind of a last ditch effort. I only thought to try it after seeing a similar sleep 1 in network.subr from FreeBSD when they bring up IPv6, possibly for similar reasons.

I'll have to test that -B flag again. I thought I did previously but still couldn't get it to work with supervise-demon for whatever reason.

**Comment by kmoore134** [comment]
And the ISO installs / boots perfect now! Merging...

**Pull request merged**
