### PR TITLE
Headset sound fix for DELL laptops, presets for Dell7577

### PR DESCRIPTION
**Pull request by yurkis**
Changes to snd_hda:
1. Added patch that fixes sound on headset jack for ALC256 codec (like DELL Inspirion 7577, Vostro 15-3568,   Latitude 7370, Inspiron 15-3552 and Inspiron 15-3567). A solution was found here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219350 , patch was got from linux snd_hda commit here: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=188702&action=diff .
2. While I was there I've added right audio groups for  Inspirion 7577 (work "out of box" now, without device.hints)

### CODE REVIEW

**Comment by yurkis** [comment]
Looks like it is not a code problem but something happened with git checkout during Jenkins job work.
@kmoore134 please review this PR. It is only one chance for me to hear sound in headphones without kernel rebuild after each update

**Comment by MiwiDots** [comment]
I'll take this pr on FreeBSD side and see if i can land the patch directly instance of here.

**Comment by MiwiDots** [comment]
Quick update I've open a review on fbsd side, https://reviews.freebsd.org/D19017

**Comment by yurkis** [comment]
Thanks a lot!
BTW, sorry for spaces. I will re-read style(9) next time

**Comment by beanpole135** [comment]
Closing this PR. Patch was accepted on the FreeBSD side of things.

**Pull request closed without merging**
