### PR TITLE
Feature json manifest

### PR DESCRIPTION
**Pull request by kmoore134**

### CODE REVIEW

**Comment by jhixson74** [comment]
I'm testing this now. I'll provide feedback as I test this out.

**Comment by jhixson74** [comment]
"make poudriere" bombed out on me because I don't have TrueOS with base poudriere. I tried to upgrade and it failed. I installed poudriere from ports and now it's failing to build lang/python27. I'll have details on that here soon.

**Comment by jhixson74** [comment]
I'm getting a signal 12 (non-existent system call) during python27 build. I suspect this is because jail and kernel mismatch. I'll have to do an update that works to test this further ;-)

**Comment by kmoore134** [comment]
No worries. I should have probably specified that you'll want to test this while running on the latest TrueOS ISO, not the legacy STABLE/UNSTABLE stuff prior to poudriere going into base. 

https://builds.ixsystems.com/jenkins/job/TrueOS%20-%20World%20CI/job/trueos-master/lastSuccessfulBuild/artifact/artifacts/

**Pull request merged**
