### PR TITLE
Add ipmitool and dmidecode to build as essential troubleshooting tools.

### PR DESCRIPTION
**Pull request by darkfiberiru**
Adding to build via manifest instead of putting into base.

### CODE REVIEW

**Comment by darkfiberiru** [comment]
Only pkg dependency is readline

**Comment by MiwiDots** [comment]
I think that should be also added to snapshot, including nginx. For our snapshot cases we need most of the time nginx anyway.

**Comment by darkfiberiru** [comment]
If we want to keep minimal there are lighter options with less dependencies then nginx. But it's only real medium sized dependency is ruby so it's not that bad. Not arguing against nginx just commenting about options if all were doing is serving a static directory.

I should of put the two utilities in all the version we build including the snapshot manifest.

**Comment by MiwiDots** [comment]
Thanks!

**Review by kmoore134 — APPROVED** [review]

**Pull request merged**
