### PR TITLE
Trueos stable build improvements

### PR DESCRIPTION
**Pull request by darkfiberiru**
Pulling back build fixes for trident and other projects to use stable

### CODE REVIEW

**Comment by beanpole135** [comment]
Could you please verify that the read/write support for /etc and /usr/local/etc is in that batch? I am not seeing that commit in the list at the moment.

Scratch that - just realized I was looking at the commits in the wrong order.
Commit f4a1a5e and 9db5c9e are the two I was looking for.

**Comment by darkfiberiru** [comment]
Ok good had me very confused

**Comment by pkgdemon** [comment]
Awesome @darkfiberiru thanks!!

**Comment by beanpole135** [comment]
Merging PR since it has now passed the CI checks.

**Pull request merged**
