### PR TITLE
Feature bhyve smbios

### PR DESCRIPTION
**Pull request by darkfiberiru**
Add ability to set smbios table type 1 from bhyve command. Merged from illumos-joyent

### CODE REVIEW

**Review by araujobsd — APPROVED** [review]
LGTM, I would only add the man page bhyve.8 changes prior to merge it. Or otherwise we can get distracted with other fun things and the man page will be never updated.

**Comment by kmoore134** [comment]
@darkfiberiru @araujobsd - I'm going to close this PR. I went looking and lo and behold, for some unknown asinine reason, the bhyve in illumos is now licensed as CDDL??

https://github.com/joyent/illumos-joyent/blob/c34f7c2c834dc5a9b871356c0f85214dc25c5881/usr/src/cmd/bhyve/bhyverun.c#L29

Its one thing to bring an existing, established CDDL program into the base (ala ZFS), however going out and polluting an existing BSD-licensed tool just seems totally unnecessary. It was bad enough when Oracle did it, but I'm not really wanting others to follow their bad example and push CDDL on the world.

**Comment by pfmooney** [comment]
@kmoore134,

The intent is that all Joyent contributions to bhyve will be dual-licensed under both the existing BSD license and the CDDL.  Initially the CDDL was added at the request of Pluribus, and only to files bearing their changes when bhyve was ported to illumos.  Those headers will live on, but provided that the Joyent copyright notice is preserved in the FreeBSD licensing header, integrating our changes to TrueOS (Or other BSD-licensed projects) should be acceptable.

It was **not** our intent to create a licensing dispute here.  We want to do whatever is necessary to make these changes available for BSD projects, so long as our copyright is maintained.

-Patrick

**Comment by araujobsd** [comment]
@pfmooney Personally I won't mind keep the Joyent copyright, even if the changes are few lines of code. But the dual licensing creates an issue for us. As I could see, you have only few bhyve files under CDDL if not only one, as Joyent is the copyright holder, it would be easier for you guys to remove the CDDL license, and it will be easier for us and the FreeBSD project to start integrate your contributions.

I have a similar patch made using libucl, but instead to commit it, I would prefer use yours and start to cooperate with you guys in so many different ways.

One way that this problem could be solved would be you guys revoke the CDDL license in that source file, if I'm not wrong, only that file in your repo is under CDDL.

The bhyve is well know as a BSD Hypervisor, adding a CDDL license will changes its concept.

**Comment by pfmooney** [comment]
As I mentioned, the CDDL was added per the wishes of Pluribus, who did the initial porting work.  It is present to cover their changes, not bhyve itself, which obviously remains BSD licensed.

We are not requesting that the Joyent CDDL copyright be preserved during upstreaming, but rather that a Joyent copyright attribution be added under the existing BSD license header on the involved files.  As a matter of follow-up, we can add the attribution for our changes to the BSD header in our repo, if that would help.

**Comment by araujobsd** [comment]
I do believe that would help a bit, but still will cost me some extra work to trackback your code and make sure those codes are not part of CDDL. Another way would be you guys upstream the code here in form of a pull request without add the CDDL license part, in this way the CDDL would be washed off, as you are the copyright holder and has no intention with your contribution to add CDDL license, that would work in a more clean way.

Regards the Joyent copyright attribution on a BSD license header, I can't see it as a problem, at least here on TrueOS.

There are several ways to attribute the contributed work, most of time people just add a reference in the commit log "Sponsored by: Company", another way is when the code really adds a new function and the copyright is added, another way is when an existent code is rewrote, the current standard is something around 25% of code, but that is more a 'feeling' than a really documented standard, but it is followed by most of contributors and the industry itself.

I would be more than happy if you guys start to upstream things here too. Either upstream on FreeBSD or here on TrueOS, will be really appreciated.

**Comment by kmoore134** [comment]
I'm going to re-open this for the time being. I want us to more or less be in line with FreeBSD's standards where it comes to adding copyrights to files, so I'm keeping track of what's been going on over on the FreeBSD reviews site:

https://reviews.freebsd.org/D15290#322488

Thanks for the clarification on CDDL though. For obvious reasons we'll need to keep our code BSD licensed only here. 

Do you guys want to update the PR soon with manpage and other changes so it merges cleanly again, then we can re-review?

**Comment by pfmooney** [comment]
Omitting the CDDL when merging this is fine, but as stated in the FreeBSD ticket you referenced, Joyent requires copyright attribution (placed in the BSD header being adequate) for its changes which rise above de minimus.

**Comment by araujobsd** [comment]
Close this pull request in favor of pr: #49

**Pull request closed without merging**
